# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SantanderTesteV2' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'Alamofire'

  # Pods for SantanderTesteV2

  target 'SantanderTesteV2Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SantanderTesteV2UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
